language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t deepaktyagi/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run deepaktyagi/react-test npm test -- --coverage

after_success:
 - docker build -t deepaktyagi/multi-client ./client
 - docker build -t deepaktyagi/multi-nginx ./nginx
 - docker build -t deepaktyagi/multi-server ./server
 - docker build -t deepaktyagi/multi-worker ./worker

#Login to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Push the images to docker hub
 - docker push deepaktyagi/multi-client
 - docker push deepaktyagi/multi-nginx
 - docker push deepaktyagi/multi-server
 - docker push deepaktyagi/multi-worker

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "multi-docker"
 env: "MultiDocker-env"
 bucket_name: "elasticbeanstalk-us-east-1-876507037317"
 bucket_path: "multi-docker"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"



